import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeaderComponent from '../src/components/Header';
import FooterComponent from '../src/components/Footer';
import Link from 'next/link'
export default function Account() {
  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <Head>
          <title>Bia Blasta</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <HeaderComponent></HeaderComponent>
      </div> 
      <div className={styles.main}>
        <div className={styles.title}>
          <h1>My Account</h1>
            <p>Welcome to your Bia Blasta Account! 
                <br/> Here you can view all your favourite recipes and plan out your weekly meals with our meal planner section
                    <br/>Select one of the tabs to see the perks of an account!
            </p>
            <Link href="/mealPlanner">Meal Planning</Link>
            <button>Favourites</button>
        </div>
      
      </div>

      <FooterComponent></FooterComponent>
    </div>   
  )
}