import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeaderComponent from '../src/components/Header';
import FooterComponent from '../src/components/Footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <Head>
          <title>Bia Blasta</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <HeaderComponent></HeaderComponent>
      </div> 
      <div className={styles.main}>
        <div className={styles.title}>
          <h1>Search Page</h1>
          <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum natus voluptatem sed ad facere necessitatibus, a, modi tempore pariatur placeat sequi aperiam quo laboriosam voluptates aliquam, voluptatum quae velit laborum.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et ipsa numquam consectetur temporibus dolor at omnis? Nesciunt impedit, inventore temporibus, quis, in quos molestias totam tempora expedita exercitationem voluptatibus. Nesciunt.</p>
        </div>
      
      </div>

      <FooterComponent></FooterComponent>
    </div>   
  )
}