import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeaderComponent from '../src/components/Header';
import FooterComponent from '../src/components/Footer';
import p1 from '../images/mixedIngredients.png';
import p2 from '../images/sampleMealA.png';
import p3 from '../images/sampleMealb.png';
import Image from 'next/image'

export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <Head>
          <title>Bia Blasta</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <HeaderComponent></HeaderComponent>
      </div> 
      <div className={styles.main}>
        <div className={styles.title}>
          <h1>Welcome to Bia Blasta</h1>
          <p>Does it always feel like you always have a handful of random ingredients with no particular direction for using them?
            <br />Do you open your fridge and just cant find any inspiration on what to cook?
            <br />Well look no further!
            <br />Bia Blasta will find you recipes that you can make right now with what you have on hand.
            <br />Within minutes you'll be browsing through recipes you can whip up for you or the family.
            <br />Find a recipe you love and want to make again?
            <br />Add the recipe to your favourites tab and come back to make again and again!
            <br />
          </p>
        </div>
        <div className={styles.image}>
            <Image src={p2} alt="Meal A" 
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"/>
            <Image src={p1} alt="Ingredients" 
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"/>
            <Image src={p3} alt="Meal B" 
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"/>
        </div>
        <div className={styles.description}>
          <h4>Here's how it works</h4>
          <p>
            Firstly Bia Blasta needs to know what ingredients you have at home
            <br />Visit the pantry page and add ALL ingredients you have
            <br />Select what you have from a list of categories such as meat, veg, fruit, grains and many more
            <br />Once all ingredients are added on the pantry page Bia Blasta will find you all recipe you can make 
            <br />wheater it's breakfast, lunch, dinner or even a little snack
            <br />Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
            <br />Vitae laboriosam provident obcaecati rerum autem, quam doloribus qui voluptatibus suscipit, 
            <br />eius doloremque dicta voluptatem non accusamus possimus error, deleniti incidunt totam.
            <br />Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vitae laboriosam provident obcaecati rerum autem, quam doloribus 
          </p>
        </div>
      </div>
      <FooterComponent></FooterComponent>
    </div> 
  )
}