const ingredientData = {
  Meat: [
    { name: "Beef" },
    { name: "Chicken" },
    { name: "Pork" },
    { name: "Lamb" },
    { name: "Beef Mince" },
    { name: "Turkey" },
    { name: "Turkey Mince" },
    { name: "Sausage" },
    { name: "Pepperoni" },
    { name: "Chorizo" },
    { name: "Bacon" },
  ],
  "Dairy-Free & Meat Substitutes": [
    { name: "Coconut Milk" },
    { name: "Almond Milk" },
    { name: "Oat Milk" },
    { name: "Soy Milk" },
    { name: "Almond Butter" },
    { name: "Non-Dairy Cream" },
    { name: "Tofu" },
    { name: "Vegan Mayonnaise" },
    { name: "Vegan Cheese" },
    { name: "Quorn Mince" },
    { name: "Quorn Chicken" },
    { name: "Quorn Sausage" },
  ],
  "Vegetables & Greens": [
    { name: "Carrots" },
    { name: "Broccoli" },
    { name: "Spinach" },
    { name: "Kale" },
    { name: "Garlic" },
    { name: "Onion" },
    { name: "Bell Pepper" },
    { name: "Tomato" },
    { name: "Potato" },
    { name: "Avacado" },
    { name: "Cucumber" },
    { name: "Sweet Corn" },
    { name: "Sweet Potato" },
    { name: "Lettuce" },
    { name: "Romaine" },
    { name: "Mushrooms" },
  ],
  Fruits: [
    { name: "Apple" },
    { name: "Banana" },
    { name: "Strawberry" },
    { name: "Blueberry" },
    { name: "Blackberry" },
    { name: "Orange" },
    { name: "Pineapple" },
    { name: "Mango" },
    { name: "Peach" },
    { name: "Grapes" },
    { name: "Pear" },
  ],
  "Dairy & Eggs": [
    { name: "Milk" },
    { name: "Eggs" },
    { name: "Butter" },
    { name: "Cream" },
    { name: "Sour Cream" },
    { name: "Yogurt" },
    { name: "Greek Yogurt" },
    { name: "Cheese" },
    { name: "Mayonnaise" },
  ],
  "Grains & Pasta": [
    { name: "Rice" },
    { name: "Quinoa" },
    { name: "Oats" },
    { name: "Spaghetti" },
    { name: "Lasagna" },
    { name: "Noodles" },
    { name: "Tagliatelle" },
    { name: "Penne Pasta" },
  ],
  "Fish & Seafood": [
    { name: "Salmon" },
    { name: "Tuna" },
    { name: "Cod" },
    { name: "Prawns" },
    { name: "Haddock" },
  ],
  Legumes: [
    { name: "Lentils" },
    { name: "Chickpeas" },
    { name: "Black beans" },
    { name: "Kidney beans" },
    { name: "Peas" },
  ],
  "Cupboard Essentials": [
    { name: "Plain Flour" },
    { name: "Self Raising Flour" },
    { name: "Baking Powder" },
    { name: "Canned Tomatoes" },
    { name: "Tomato Purée" },
  ],
};

export default ingredientData;
