import Head from 'next/head'
import styles from '../styles/Account.module.css'
import HeaderComponent from '../src/components/Header';
import FooterComponent from '../src/components/Footer';

export default function mealPlanner() {
  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <Head>
          <title>Bia Blasta</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <HeaderComponent></HeaderComponent>
      </div>
      <div className={styles.main}>
        <div className={styles.title}>
          <h1>Meal Planner</h1>
          <h3>List</h3>
          <p>Pick out which recipes you want to make for the week, then when your finished we will generate a list of all ingredients you need!</p>
        <p>**Display all recipes in database **</p>
        </div>
        <div className={styles.description}>
            <div className={styles.table}>
                <h2>Monday</h2>
                <h4>Breakfast</h4>
                <p>**Recipe**</p>
                <h4>Lunch</h4>
                <p>**Recipe**</p>
                <h4>Dinner</h4>
                <p>**Recipe**</p>
                <h4>Snacks</h4>
                <p>**Recipe**</p>
            </div>
            <div className={styles.table}>
                <h2>Tuesday</h2>
                <h4>Breakfast</h4>
                <p>**Recipe**</p>
                <h4>Lunch</h4>
                <p>**Recipe**</p>
                <h4>Dinner</h4>
                <p>**Recipe**</p>
                <h4>Snacks</h4>
                <p>**Recipe**</p>
            </div>
            <div className={styles.table}>
                <h2>Wednesday</h2>
                <h4>Breakfast</h4>
                <p>**Recipe**</p>
                <h4>Lunch</h4>
                <p>**Recipe**</p>
                <h4>Dinner</h4>
                <p>**Recipe**</p>
                <h4>Snacks</h4>
                <p>**Recipe**</p>
            </div>
            <div className={styles.table}>
                <h2>Thursday</h2>
                <h4>Breakfast</h4>
                <p>**Recipe**</p>
                <h4>Lunch</h4>
                <p>**Recipe**</p>
                <h4>Dinner</h4>
                <p>**Recipe**</p>
                <h4>Snacks</h4>
                <p>**Recipe**</p>
            </div>
            <div className={styles.table}>
                <h2>Friday</h2>
                <h4>Breakfast</h4>
                <p>**Recipe**</p>
                <h4>Lunch</h4>
                <p>**Recipe**</p>
                <h4>Dinner</h4>
                <p>**Recipe**</p>
                <h4>Snacks</h4>
                <p>**Recipe**</p>
            </div>
            <div className={styles.table}>
                <h2>Saturday</h2>
                <h4>Breakfast</h4>
                <p>**Recipe**</p>
                <h4>Lunch</h4>
                <p>**Recipe**</p>
                <h4>Dinner</h4>
                <p>**Recipe**</p>
                <h4>Snacks</h4>
                <p>**Recipe**</p>
            </div>
            <div className={styles.table}>
                <h2>Sunday</h2>
                <h4>Breakfast</h4>
                <p>**Recipe**</p>
                <h4>Lunch</h4>
                <p>**Recipe**</p>
                <h4>Dinner</h4>
                <p>**Recipe**</p>
                <h4>Snacks</h4>
                <p>**Recipe**</p>
            </div>
        </div>
    </div>
      <FooterComponent></FooterComponent>
    </div>
  )
}